services:
  postgres:
    image: postgres:latest
    container_name: pg-mediary
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U devuser -d devdb"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

volumes:
  pgdata:
